/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desafionintendo;

import java.awt.Color;
import java.awt.color.ColorSpace;
import java.awt.image.BufferedImage;
import java.awt.image.BufferedImageOp;
import java.awt.image.ColorConvertOp;
import java.awt.image.Raster;
import java.awt.image.RescaleOp;
import java.awt.image.WritableRaster;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.imageio.stream.ImageOutputStream;
import javax.swing.ImageIcon;

//import com.sun.tools.sjavac.Log.Level;

/**
 *
 * @author patic
 */
public class Main extends javax.swing.JFrame {

	/**
	 * Creates new form Main
	 */
	public Main() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMaximumSize(new java.awt.Dimension(540, 540));
		setPreferredSize(new java.awt.Dimension(700, 500));
		setResizable(false);
		setSize(new java.awt.Dimension(540, 540));

		jButton1.setText("Remover ruídos");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel3.setText("Selecione a ação desejada:");

		jButton2.setText("Diminuir brilho em 20%");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("Contorno");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("Diminuir contraste em 30%");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setText("Suavizar");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setText("Negativo");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(51, 51, 51)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGroup(layout.createSequentialGroup()
						.addGap(249, 249, 249)
						.addComponent(jLabel3))
				.addGroup(layout.createSequentialGroup()
						.addGap(99, 99, 99)
						.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(34, 34, 34)
						.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGroup(layout.createSequentialGroup()
						.addGap(99, 99, 99)
						.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(34, 34, 34)
						.addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGroup(layout.createSequentialGroup()
						.addGap(99, 99, 99)
						.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(34, 34, 34)
						.addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(56, 56, 56)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addComponent(jLabel3)
						.addGap(29, 29, 29)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButton1)
								.addComponent(jButton4))
						.addGap(11, 11, 11)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButton2)
								.addComponent(jButton5))
						.addGap(13, 13, 13)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButton3)
								.addComponent(jButton6)))
				);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		jLabel2.setIcon(null);
		jLabel1.setIcon(null);
		ImageIcon icon=new ImageIcon("src/Imagens/Imagem1.jpg");        
		jLabel1.setIcon(icon);

		BufferedImage image = null; 
		try {
			image = ImageIO.read(new File("src/Imagens/Imagem1.jpg"));
		} catch (IOException ex) {
			// Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
		}

		BufferedImageOp op = new ColorConvertOp(
				ColorSpace.getInstance(ColorSpace.CS_GRAY), null);
		jLabel2.setIcon(new ImageIcon(op.filter(image, null)));

	}//GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		jLabel2.setIcon(null);
		jLabel1.setIcon(null);
		ImageIcon icon=new ImageIcon("src/Imagens/Imagem2.jpg");        
		jLabel1.setIcon(icon);

		BufferedImage image = null;
		try {
			image = ImageIO.read(new File("src/Imagens/Imagem2.jpg"));
		} catch (IOException ex) {
			// Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
		}
		int pixel = 0;
		int brilho = -20;

		for (int i = 0; i < image.getWidth(); i++) {
			for (int j = 0; j < image.getHeight(); j++) {
				Color c = new Color(image.getRGB(i, j));
				int vermelho = c.getRed();
				int verde = c.getGreen();
				int azul = c.getBlue();

				vermelho = (1 * vermelho + brilho);
				verde = (1 * verde + brilho);
				azul = (1 * azul + brilho);

				vermelho = Math.max(Math.min(255, vermelho), 0);
				verde = Math.max(Math.min(255, verde), 0);
				azul = Math.max(Math.min(255, azul), 0);

				Color pixel_final = new Color((int) vermelho, (int) verde, (int) azul);
				image.setRGB(i, j, pixel_final.getRGB());

			}
		}
		jLabel2.setIcon(new ImageIcon(image, null));

	}//GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		jLabel2.setIcon(null);
		jLabel1.setIcon(null);
		ImageIcon icon=new ImageIcon("src/Imagens/Imagem3.jpg"); 
		jLabel1.setIcon(icon);

		BufferedImage image = null;
		try {
			image = ImageIO.read(new File("src/Imagens/Imagem3.jpg"));
		} catch (IOException ex) {
			// Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
		}		

		int x = image.getWidth();
        int y = image.getHeight();

        int maxGval = 0;
        int[][] edgeColors = new int[x][y];
        int maxGradient = -1;

        for (int i = 1; i < x - 1; i++) {
            for (int j = 1; j < y - 1; j++) {

                int val00 = getGrayScale(image.getRGB(i - 1, j - 1));
                int val01 = getGrayScale(image.getRGB(i - 1, j));
                int val02 = getGrayScale(image.getRGB(i - 1, j + 1));

                int val10 = getGrayScale(image.getRGB(i, j - 1));
                int val11 = getGrayScale(image.getRGB(i, j));
                int val12 = getGrayScale(image.getRGB(i, j + 1));

                int val20 = getGrayScale(image.getRGB(i + 1, j - 1));
                int val21 = getGrayScale(image.getRGB(i + 1, j));
                int val22 = getGrayScale(image.getRGB(i + 1, j + 1));

                int gx =  ((-1 * val00) + (0 * val01) + (1 * val02)) 
                        + ((-2 * val10) + (0 * val11) + (2 * val12))
                        + ((-1 * val20) + (0 * val21) + (1 * val22));

                int gy =  ((-1 * val00) + (-2 * val01) + (-1 * val02))
                        + ((0 * val10) + (0 * val11) + (0 * val12))
                        + ((1 * val20) + (2 * val21) + (1 * val22));

                double gval = Math.sqrt((gx * gx) + (gy * gy));
                int g = (int) gval;

                if(maxGradient < g) {
                    maxGradient = g;
                }

                edgeColors[i][j] = g;
            }
        }

        double scale = 255.0 / maxGradient;

        for (int i = 1; i < x - 1; i++) {
            for (int j = 1; j < y - 1; j++) {
                int edgeColor = edgeColors[i][j];
                edgeColor = (int)(edgeColor * scale);
                edgeColor = 0xff000000 | (edgeColor << 16) | (edgeColor << 8) | edgeColor;

                image.setRGB(i, j, edgeColor);
            }
        }        
        
		jLabel2.setIcon(new ImageIcon(image, null));
	}//GEN-LAST:event_jButton3ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
		jLabel2.setIcon(null);
		jLabel1.setIcon(null);
		ImageIcon icon=new ImageIcon("src/Imagens/Imagem4.jpg");        
		jLabel1.setIcon(icon);

		BufferedImage image = null;
		try {
			image = ImageIO.read(new File("src/Imagens/Imagem4.jpg"));
		} catch (IOException ex) {
			// Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
		}

		BufferedImage input = image;
		BufferedImage output = new BufferedImage(input.getWidth(),
				input.getHeight(), BufferedImage.TYPE_INT_RGB);

		float scaleFactor = 1.0f;
		float offset = -30;

		RescaleOp rescale = new RescaleOp(scaleFactor, offset, null);
		jLabel2.setIcon(new ImageIcon(rescale.filter(input, output)));

	}//GEN-LAST:event_jButton4ActionPerformed

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
		jLabel2.setIcon(null);
		jLabel1.setIcon(null);
		ImageIcon icon=new ImageIcon("src/Imagens/Imagem5.jpg");        
		jLabel1.setIcon(icon);

		BufferedImage image = null;
		try {
			image = ImageIO.read(new File("src/Imagens/Imagem5.jpg"));
		} catch (IOException ex) {
			// Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
		}

		int width = image.getWidth();
		int height = image.getHeight();

		int[] vet;

		vet = new int[9];

		for (int i = 0; i < width; i++) {
			for (int j = 0; j < height; j++) {

				for (int coluna = i - 1; coluna <= i + 1; coluna++) {
					for (int linha = j - 1; linha <= j + 1; linha++) {
						image.setRGB(coluna, linha, new Color(vet[5], vet[5], vet[5]).getRGB());
					}
				}

			}
		}

		jLabel2.setIcon(new ImageIcon(image, null));
	}//GEN-LAST:event_jButton5ActionPerformed

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
		jLabel2.setIcon(null);
		jLabel1.setIcon(null);
		ImageIcon icon=new ImageIcon("src/Imagens/Imagem6.jpg");        
		jLabel1.setIcon(icon);

		BufferedImage image = null;
		try {
			image = ImageIO.read(new File("src/Imagens/Imagem6.jpg"));
		} catch (IOException ex) {
			// Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
		}

		int width = image.getWidth();
		int height = image.getHeight();
		for (int i = 0; i < width; i++) {
			for (int j = 0; j < height; j++) {
				Color c = new Color(image.getRGB(i, j));
				int vermelho = 255 - c.getRed();
				int verde = 255 - c.getGreen();
				int azul = 255 - c.getBlue();
				Color color = new Color(vermelho, verde, azul);
				image.setRGB(i, j, color.getRGB());
			}
		}
		jLabel2.setIcon(new ImageIcon(image, null));
	}//GEN-LAST:event_jButton6ActionPerformed

	 public static int  getGrayScale(int rgb) {
	        int r = (rgb >> 16) & 0xff;
	        int g = (rgb >> 8) & 0xff;
	        int b = (rgb) & 0xff;

	        //from https://en.wikipedia.org/wiki/Grayscale, calculating luminance
	        int gray = (int)(0.2126 * r + 0.7152 * g + 0.0722 * b);
	        //int gray = (r + g + b) / 3;

	        return gray;
	    }
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	// End of variables declaration//GEN-END:variables
}
